language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

before_script:
    - "if [[ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]]; then pyrus install pecl/redis; pyrus build pecl/redis; echo \"extension = redis.so\" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi"
    - "composer install"

script:
    - phpunit
    - ./vendor/bin/phpspec run -fpretty
